# Generated by Django 5.2.6 on 2026-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_application_message_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20),
        ),
    ]
