# Generated by Django 5.2.6 on 2026-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_hired_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('painting', 'Painting & Decorating'), ('landscaping', 'Landscaping'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=50),
        ),
    ]
