# Generated by Django 5.2.6 on 2026-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ US Dollar'), ('GBP', '£ British Pound'), ('CAD', 'CA$ Canadian Dollar'), ('AUD', 'AU$ Australian Dollar')], default='EUR', max_length=3),
        ),
    ]
