# Generated by Django 5.2.6 on 2026-03-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='completed_by_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
