# Generated by Django 5.2.7 on 2026-05-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_completed_by_client_job_completed_by_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='jobs.job')),
            ],
        ),
    ]
